//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HimLetters.ServiceReferenceLetterDetails {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="getLetterDetail_Results", Namespace="http://schemas.datacontract.org/2004/07/HimLettersWCFService")]
    [System.SerializableAttribute()]
    public partial class getLetterDetail_Results : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Chart_On_HoldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Charts_To_IncludeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Deficiencies_To_IncludeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Deficient_Day_Range_EndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Deficient_Day_Range_StartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Include_DocumentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Include_VisitsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Physicians_To_IncludeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Chart_On_Hold {
            get {
                return this.Chart_On_HoldField;
            }
            set {
                if ((object.ReferenceEquals(this.Chart_On_HoldField, value) != true)) {
                    this.Chart_On_HoldField = value;
                    this.RaisePropertyChanged("Chart_On_Hold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Charts_To_Include {
            get {
                return this.Charts_To_IncludeField;
            }
            set {
                if ((object.ReferenceEquals(this.Charts_To_IncludeField, value) != true)) {
                    this.Charts_To_IncludeField = value;
                    this.RaisePropertyChanged("Charts_To_Include");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Deficiencies_To_Include {
            get {
                return this.Deficiencies_To_IncludeField;
            }
            set {
                if ((object.ReferenceEquals(this.Deficiencies_To_IncludeField, value) != true)) {
                    this.Deficiencies_To_IncludeField = value;
                    this.RaisePropertyChanged("Deficiencies_To_Include");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Deficient_Day_Range_End {
            get {
                return this.Deficient_Day_Range_EndField;
            }
            set {
                if ((object.ReferenceEquals(this.Deficient_Day_Range_EndField, value) != true)) {
                    this.Deficient_Day_Range_EndField = value;
                    this.RaisePropertyChanged("Deficient_Day_Range_End");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Deficient_Day_Range_Start {
            get {
                return this.Deficient_Day_Range_StartField;
            }
            set {
                if ((object.ReferenceEquals(this.Deficient_Day_Range_StartField, value) != true)) {
                    this.Deficient_Day_Range_StartField = value;
                    this.RaisePropertyChanged("Deficient_Day_Range_Start");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Include_Documents {
            get {
                return this.Include_DocumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.Include_DocumentsField, value) != true)) {
                    this.Include_DocumentsField = value;
                    this.RaisePropertyChanged("Include_Documents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Include_Visits {
            get {
                return this.Include_VisitsField;
            }
            set {
                if ((object.ReferenceEquals(this.Include_VisitsField, value) != true)) {
                    this.Include_VisitsField = value;
                    this.RaisePropertyChanged("Include_Visits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Physicians_To_Include {
            get {
                return this.Physicians_To_IncludeField;
            }
            set {
                if ((object.ReferenceEquals(this.Physicians_To_IncludeField, value) != true)) {
                    this.Physicians_To_IncludeField = value;
                    this.RaisePropertyChanged("Physicians_To_Include");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LetterDetailsException", Namespace="http://schemas.datacontract.org/2004/07/HimLettersWCFService")]
    [System.SerializableAttribute()]
    public partial class LetterDetailsException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceLetterDetails.IServiceLetterDetails")]
    public interface IServiceLetterDetails {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLetterDetails/GetLetterDetails", ReplyAction="http://tempuri.org/IServiceLetterDetails/GetLetterDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HimLetters.ServiceReferenceLetterDetails.LetterDetailsException), Action="http://tempuri.org/IServiceLetterDetails/GetLetterDetailsLetterDetailsExceptionFa" +
            "ult", Name="LetterDetailsException", Namespace="http://schemas.datacontract.org/2004/07/HimLettersWCFService")]
        HimLetters.ServiceReferenceLetterDetails.getLetterDetail_Results[] GetLetterDetails(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLetterDetails/GetLetterDetails", ReplyAction="http://tempuri.org/IServiceLetterDetails/GetLetterDetailsResponse")]
        System.Threading.Tasks.Task<HimLetters.ServiceReferenceLetterDetails.getLetterDetail_Results[]> GetLetterDetailsAsync(string Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceLetterDetailsChannel : HimLetters.ServiceReferenceLetterDetails.IServiceLetterDetails, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceLetterDetailsClient : System.ServiceModel.ClientBase<HimLetters.ServiceReferenceLetterDetails.IServiceLetterDetails>, HimLetters.ServiceReferenceLetterDetails.IServiceLetterDetails {
        
        public ServiceLetterDetailsClient() {
        }
        
        public ServiceLetterDetailsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceLetterDetailsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceLetterDetailsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceLetterDetailsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HimLetters.ServiceReferenceLetterDetails.getLetterDetail_Results[] GetLetterDetails(string Id) {
            return base.Channel.GetLetterDetails(Id);
        }
        
        public System.Threading.Tasks.Task<HimLetters.ServiceReferenceLetterDetails.getLetterDetail_Results[]> GetLetterDetailsAsync(string Id) {
            return base.Channel.GetLetterDetailsAsync(Id);
        }
    }
}
