//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HimLetters.ServiceReferencePassword {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="getPass_Results", Namespace="http://schemas.datacontract.org/2004/07/HimLettersWCFService")]
    [System.SerializableAttribute()]
    public partial class getPass_Results : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferencePassword.IServicePassword")]
    public interface IServicePassword {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePassword/GetPassword", ReplyAction="http://tempuri.org/IServicePassword/GetPasswordResponse")]
        HimLetters.ServiceReferencePassword.getPass_Results[] GetPassword(string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePassword/GetPassword", ReplyAction="http://tempuri.org/IServicePassword/GetPasswordResponse")]
        System.Threading.Tasks.Task<HimLetters.ServiceReferencePassword.getPass_Results[]> GetPasswordAsync(string Username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicePasswordChannel : HimLetters.ServiceReferencePassword.IServicePassword, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicePasswordClient : System.ServiceModel.ClientBase<HimLetters.ServiceReferencePassword.IServicePassword>, HimLetters.ServiceReferencePassword.IServicePassword {
        
        public ServicePasswordClient() {
        }
        
        public ServicePasswordClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicePasswordClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePasswordClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePasswordClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HimLetters.ServiceReferencePassword.getPass_Results[] GetPassword(string Username) {
            return base.Channel.GetPassword(Username);
        }
        
        public System.Threading.Tasks.Task<HimLetters.ServiceReferencePassword.getPass_Results[]> GetPasswordAsync(string Username) {
            return base.Channel.GetPasswordAsync(Username);
        }
    }
}
